// Auto-generated by svelte-realtime - do not edit
// Provides client-side types for $live/ imports

declare module '$live/editor' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const applyMutation: ({ collection, patches }) => Promise<any>;
  export const foldersStream: StreamStore<ClosureTableNode[] | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<ClosureTableNode[]> };
  export const empty: Readable<undefined>;
}

declare module '$live/tag-folder' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const applyTagFolderPatches: (patches: TravelPatches["patches"][number]) => Promise<any>;
  export const tagFolderPatches: StreamStore<any | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}

declare module '$live/tags' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const applyTagPatches: (patches: TravelPatches["patches"][number]) => Promise<any>;
  export const tagPatches: StreamStore<any | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const empty: Readable<undefined>;
}
