// Auto-generated by svelte-realtime - do not edit
// Provides client-side types for $live/ imports

declare module '$live/counter' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const increment: () => Promise<any>;
  export const counter: StreamStore<any | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<any> };
  export const tree: StreamStore<ClosureTableNode | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<ClosureTableNode> };
  export const empty: Readable<undefined>;
}

declare module '$live/editor' {
  import type { StreamStore, RpcError } from 'svelte-realtime/client';
  import type { Readable } from 'svelte/store';

  export const applyMutation: ({ collection, patches }) => Promise<any>;
  export const tagsStream: StreamStore<Record<string, TagSelect> | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<Record<string, TagSelect>> };
  export const devicesStream: StreamStore<Record<string, Device> | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<Record<string, Device>> };
  export const displaysStream: StreamStore<Record<string, Display> | undefined | { error: RpcError }> & { load(platform: any, options?: { args?: any[]; user?: any }): Promise<Record<string, Display>> };
  export const empty: Readable<undefined>;
}
